// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace NorthwindApi.Models
{
    public partial class Shipper
    {
        public short ShipperId { get; set; }
        public string CompanyName { get; set; }
        public string Phone { get; set; }
    }
}