// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using NorthwindApi.Data;
using NorthwindApi.Models;
using System;


namespace NorthwindApi.Data.Configurations
{
    public partial class CategoryConfiguration : IEntityTypeConfiguration<Category>
    {
        public void Configure(EntityTypeBuilder<Category> entity)
        {
            entity.ToTable("categories");

            entity.Property(e => e.CategoryId)
                .HasColumnName("category_id")
                .ValueGeneratedNever();

            entity.Property(e => e.CategoryName)
                .IsRequired()
                .HasColumnName("category_name")
                .HasMaxLength(15);

            entity.Property(e => e.Description).HasColumnName("description");

            entity.Property(e => e.Picture).HasColumnName("picture");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Category> entity);
    }
}
