// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using NorthwindApi.Data;
using NorthwindApi.Models;
using System;


namespace NorthwindApi.Data.Configurations
{
    public partial class EmployeeConfiguration : IEntityTypeConfiguration<Employee>
    {
        public void Configure(EntityTypeBuilder<Employee> entity)
        {
            entity.ToTable("employees");

            entity.Property(e => e.EmployeeId)
                .HasColumnName("employee_id")
                .ValueGeneratedNever();

            entity.Property(e => e.Address)
                .HasColumnName("address")
                .HasMaxLength(60);

            entity.Property(e => e.BirthDate)
                .HasColumnName("birth_date")
                .HasColumnType("date");

            entity.Property(e => e.City)
                .HasColumnName("city")
                .HasMaxLength(15);

            entity.Property(e => e.Country)
                .HasColumnName("country")
                .HasMaxLength(15);

            entity.Property(e => e.Extension)
                .HasColumnName("extension")
                .HasMaxLength(4);

            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasColumnName("first_name")
                .HasMaxLength(10);

            entity.Property(e => e.HireDate)
                .HasColumnName("hire_date")
                .HasColumnType("date");

            entity.Property(e => e.HomePhone)
                .HasColumnName("home_phone")
                .HasMaxLength(24);

            entity.Property(e => e.LastName)
                .IsRequired()
                .HasColumnName("last_name")
                .HasMaxLength(20);

            entity.Property(e => e.Notes).HasColumnName("notes");

            entity.Property(e => e.Photo).HasColumnName("photo");

            entity.Property(e => e.PhotoPath)
                .HasColumnName("photo_path")
                .HasMaxLength(255);

            entity.Property(e => e.PostalCode)
                .HasColumnName("postal_code")
                .HasMaxLength(10);

            entity.Property(e => e.Region)
                .HasColumnName("region")
                .HasMaxLength(15);

            entity.Property(e => e.ReportsTo).HasColumnName("reports_to");

            entity.Property(e => e.Title)
                .HasColumnName("title")
                .HasMaxLength(30);

            entity.Property(e => e.TitleOfCourtesy)
                .HasColumnName("title_of_courtesy")
                .HasMaxLength(25);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Employee> entity);
    }
}
