// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using NorthwindApi.Data;
using NorthwindApi.Models;
using System;


namespace NorthwindApi.Data.Configurations
{
    public partial class EmployeeTerritoryConfiguration : IEntityTypeConfiguration<EmployeeTerritory>
    {
        public void Configure(EntityTypeBuilder<EmployeeTerritory> entity)
        {
            entity.HasKey(e => new { e.EmployeeId, e.TerritoryId })
                .HasName("employee_territories_pkey");

            entity.ToTable("employee_territories");

            entity.Property(e => e.EmployeeId).HasColumnName("employee_id");

            entity.Property(e => e.TerritoryId)
                .HasColumnName("territory_id")
                .HasMaxLength(20);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EmployeeTerritory> entity);
    }
}
