// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using NorthwindApi.Data;
using NorthwindApi.Models;
using System;


namespace NorthwindApi.Data.Configurations
{
    public partial class OrderConfiguration : IEntityTypeConfiguration<Order>
    {
        public void Configure(EntityTypeBuilder<Order> entity)
        {
            entity.ToTable("orders");

            entity.Property(e => e.OrderId)
                .HasColumnName("order_id")
                .ValueGeneratedNever();

            entity.Property(e => e.CustomerId)
                .HasColumnName("customer_id")
                .HasColumnType("char");

            entity.Property(e => e.EmployeeId).HasColumnName("employee_id");

            entity.Property(e => e.Freight).HasColumnName("freight");

            entity.Property(e => e.OrderDate)
                .HasColumnName("order_date")
                .HasColumnType("date");

            entity.Property(e => e.RequiredDate)
                .HasColumnName("required_date")
                .HasColumnType("date");

            entity.Property(e => e.ShipAddress)
                .HasColumnName("ship_address")
                .HasMaxLength(60);

            entity.Property(e => e.ShipCity)
                .HasColumnName("ship_city")
                .HasMaxLength(15);

            entity.Property(e => e.ShipCountry)
                .HasColumnName("ship_country")
                .HasMaxLength(15);

            entity.Property(e => e.ShipName)
                .HasColumnName("ship_name")
                .HasMaxLength(40);

            entity.Property(e => e.ShipPostalCode)
                .HasColumnName("ship_postal_code")
                .HasMaxLength(10);

            entity.Property(e => e.ShipRegion)
                .HasColumnName("ship_region")
                .HasMaxLength(15);

            entity.Property(e => e.ShipVia).HasColumnName("ship_via");

            entity.Property(e => e.ShippedDate)
                .HasColumnName("shipped_date")
                .HasColumnType("date");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Order> entity);
    }
}
