// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using NorthwindApi.Data;
using NorthwindApi.Models;
using System;


namespace NorthwindApi.Data.Configurations
{
    public partial class ProductConfiguration : IEntityTypeConfiguration<Product>
    {
        public void Configure(EntityTypeBuilder<Product> entity)
        {
            entity.ToTable("products");

            entity.Property(e => e.ProductId)
                .HasColumnName("product_id")
                .ValueGeneratedNever();

            entity.Property(e => e.CategoryId).HasColumnName("category_id");

            entity.Property(e => e.Discontinued).HasColumnName("discontinued");

            entity.Property(e => e.ProductName)
                .IsRequired()
                .HasColumnName("product_name")
                .HasMaxLength(40);

            entity.Property(e => e.QuantityPerUnit)
                .HasColumnName("quantity_per_unit")
                .HasMaxLength(20);

            entity.Property(e => e.ReorderLevel).HasColumnName("reorder_level");

            entity.Property(e => e.SupplierId).HasColumnName("supplier_id");

            entity.Property(e => e.UnitPrice).HasColumnName("unit_price");

            entity.Property(e => e.UnitsInStock).HasColumnName("units_in_stock");

            entity.Property(e => e.UnitsOnOrder).HasColumnName("units_on_order");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Product> entity);
    }
}
