// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using NorthwindApi.Data;
using NorthwindApi.Models;
using System;


namespace NorthwindApi.Data.Configurations
{
    public partial class RegionConfiguration : IEntityTypeConfiguration<Region>
    {
        public void Configure(EntityTypeBuilder<Region> entity)
        {
            entity.ToTable("region");

            entity.Property(e => e.RegionId)
                .HasColumnName("region_id")
                .ValueGeneratedNever();

            entity.Property(e => e.RegionDescription)
                .IsRequired()
                .HasColumnName("region_description")
                .HasColumnType("char");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Region> entity);
    }
}
