// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using NorthwindApi.Data;
using NorthwindApi.Models;
using System;


namespace NorthwindApi.Data.Configurations
{
    public partial class TerritoryConfiguration : IEntityTypeConfiguration<Territory>
    {
        public void Configure(EntityTypeBuilder<Territory> entity)
        {
            entity.ToTable("territories");

            entity.Property(e => e.TerritoryId)
                .HasColumnName("territory_id")
                .HasMaxLength(20);

            entity.Property(e => e.RegionId).HasColumnName("region_id");

            entity.Property(e => e.TerritoryDescription)
                .IsRequired()
                .HasColumnName("territory_description")
                .HasColumnType("char");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Territory> entity);
    }
}
