// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using NorthwindApi.Data;
using NorthwindApi.Models;
using System;


namespace NorthwindApi.Data.Configurations
{
    public partial class UsStateConfiguration : IEntityTypeConfiguration<UsState>
    {
        public void Configure(EntityTypeBuilder<UsState> entity)
        {
            entity.HasKey(e => e.StateId)
                .HasName("us_states_pkey");

            entity.ToTable("us_states");

            entity.Property(e => e.StateId)
                .HasColumnName("state_id")
                .ValueGeneratedNever();

            entity.Property(e => e.StateAbbr)
                .HasColumnName("state_abbr")
                .HasMaxLength(2);

            entity.Property(e => e.StateName)
                .HasColumnName("state_name")
                .HasMaxLength(100);

            entity.Property(e => e.StateRegion)
                .HasColumnName("state_region")
                .HasMaxLength(50);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<UsState> entity);
    }
}
